### ISSUE TITLE
Unexpected output when using env-sync w/o an action

### ISSUE THREAD

**Issue by jms-pantheon** [pantheon-systems/terminus-autopilot-plugin#20]
Running `terminus site:autopilot:env-sync` without `:enable` or `:disable` responds with "enabled"

<img width="553" alt="image" src="https://user-images.githubusercontent.com/91161717/202807850-36f71f59-cb9d-4ae0-9ce8-40713b919f18.png">

**Comment by scottbuscemi** [comment]
This is expected behavior - it is returning the current environment syncing status. Worthwhile to add this to the documentation though!
